/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2016-11-24 14:43:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/dialog/warn.jsp", Long.valueOf(1479995376000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("    <title>高速数据流采集器</title>\n");
      out.write("    <meta name=\"Keywords\" content=\"\">\n");
      out.write("    <meta name=\"Description\" content=\"\">\n");
      out.write("    <meta name=\"Author\" content=\"JacksonCode\">\n");
      out.write("    <link id=\"bs-css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/css/charisma-app.css\" rel=\"stylesheet\"> \n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/img/logo.png\">\n");
      out.write("    \n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/bower_components/jquery/jquery.min.js\"></script>\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/bower_components/bootstrap/dist/js/bootstrap.min.js\"></script> \n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction onSubmit(){\n");
      out.write("\t\t\tvar user = $(\"input[name=username]\").val();\n");
      out.write("\t\t\tvar pwd = $(\"input[name=password]\").val();\n");
      out.write("\t\t\tif(user==null || user.trim()==\"\"){\n");
      out.write("\t\t\t\tshowDialog(\" 请 输 入 用 户 名  \");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}else if(pwd==null || pwd.trim()==\"\"){\n");
      out.write("\t\t\t\tshowDialog(\" 请 输 入 密 码  \");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t};\n");
      out.write("\t\tfunction showDialog(msg){\n");
      out.write("\t\t\t$('#warn_msg').html(msg);\n");
      out.write("\t        $('#warn').modal('show');\n");
      out.write("\t    };\n");
      out.write("\t</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"ch-container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12 center login-header\">\n");
      out.write("            <h2  style=\"letter-spacing:30px;margin-left:36px;\">高速数据流采集器</h2>\n");
      out.write("        </div>\n");
      out.write("    </div> \n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"well col-md-5 center login-box\">\n");
      out.write("            <div class=\"alert alert-info\" style=\"letter-spacing:5px;\"> 高速数据流采集器开发小组  </div>\n");
      out.write("            <form class=\"form-horizontal\" onsubmit=\"return onSubmit();\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/authentication\" method=\"post\">\n");
      out.write("                <fieldset>\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\" style=\"color:rgb(141, 66, 49);\"></i></span>\n");
      out.write("                        <input name=\"username\" type=\"text\"  placeholder=\"请 输 入 用 户 名\" class=\"form-control\" value=\"\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"></div><br>\n");
      out.write("\n");
      out.write("                    <div class=\"input-group input-group-lg\">\n");
      out.write("                        <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\" style=\"color:rgb(141, 66, 49);\"></i></span>\n");
      out.write("                        <input name=\"password\" type=\"password\"  placeholder=\"请 输 入 密 码\" class=\"form-control\" value=\"\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"></div>\n");
      out.write("                    <p class=\"center col-md-5\">\n");
      out.write("                        <span id=\"error\" style=\"color:#b50000;font:24px;font-weight:700;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">登&nbsp;录</button>\n");
      out.write("                    </p>\n");
      out.write("                </fieldset>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div> \n");
      out.write("</div> \n");
      out.write("\n");
      out.write("</div> \n");
      out.write("\n");
      out.write("<div id=\"warn\" class=\"modal fade bs-example-modal-sm\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"false\">\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("\t    <div class=\"modal-header\">\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("\t        <h3 style=\"width:100px;margin:0 auto;color:#b00;font:28px 600;text-align:center;\">警&nbsp;告</h3>\n");
      out.write("\t    </div>\n");
      out.write("\t    <div class=\"modal-body\">\n");
      out.write("\t       <span style=\"color:rgb(153,27,27);font-size:18px;display:block;width:270px;margin:0 auto;text-align:center;\" id=\"warn_msg\"></span>\n");
      out.write("\t    </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /login.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /login.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/login.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    }
    return false;
  }
}
